#ifndef __PLACEHOLDER_MYPROJ_MYWINKMLIB_HPP__
#define __PLACEHOLDER_MYPROJ_MYWINKMLIB_HPP__ 

namespace PLACEHOLDER_MYPROJ_MYWINKMLIB
{
void func();
}

#endif // __PLACEHOLDER_MYPROJ_MYWINKMLIB_HPP__
