
#ifndef __PLACEHOLDER_MYPROJ_MYLIB_H__
#define __PLACEHOLDER_MYPROJ_MYLIB_H__

#ifdef MYLIB_BUILT_AS_STATIC
#  define PLACEHOLDER_MYPROJ_MYLIB_EXPORT
#  define PLACEHOLDER_MYPROJ_MYLIB_NO_EXPORT
#else
#  ifndef PLACEHOLDER_MYPROJ_MYLIB_EXPORT
#    ifdef PLACEHOLDER_MYPROJ_MYLIB_EXPORTS
        /* We are building this library */
#      define PLACEHOLDER_MYPROJ_MYLIB_EXPORT __declspec(dllexport)
#    else
        /* We are using this library */
#      define PLACEHOLDER_MYPROJ_MYLIB_EXPORT __declspec(dllimport)
#    endif
#  endif

#  ifndef PLACEHOLDER_MYPROJ_MYLIB_NO_EXPORT
#    define PLACEHOLDER_MYPROJ_MYLIB_NO_EXPORT 
#  endif
#endif

#ifndef PLACEHOLDER_MYPROJ_MYLIB_DEPRECATED
#  define PLACEHOLDER_MYPROJ_MYLIB_DEPRECATED __declspec(deprecated)
#endif

#ifndef PLACEHOLDER_MYPROJ_MYLIB_DEPRECATED_EXPORT
#  define PLACEHOLDER_MYPROJ_MYLIB_DEPRECATED_EXPORT PLACEHOLDER_MYPROJ_MYLIB_EXPORT PLACEHOLDER_MYPROJ_MYLIB_DEPRECATED
#endif

#ifndef PLACEHOLDER_MYPROJ_MYLIB_DEPRECATED_NO_EXPORT
#  define PLACEHOLDER_MYPROJ_MYLIB_DEPRECATED_NO_EXPORT PLACEHOLDER_MYPROJ_MYLIB_NO_EXPORT PLACEHOLDER_MYPROJ_MYLIB_DEPRECATED
#endif

#if 0 /* DEFINE_NO_DEPRECATED */
#  ifndef PLACEHOLDER_MYPROJ_MYLIB_NO_DEPRECATED
#    define PLACEHOLDER_MYPROJ_MYLIB_NO_DEPRECATED
#  endif
#endif

#endif /* __PLACEHOLDER_MYPROJ_MYLIB_H__ */
