#ifndef __PLACEHOLDER_MYPROJ_MYLIB_HPP__
#define __PLACEHOLDER_MYPROJ_MYLIB_HPP__

#include "PLACEHOLDER_MYPROJ_MYLIB_Export.h"

namespace PLACEHOLDER_MYPROJ_MYLIB
{

PLACEHOLDER_MYPROJ_MYLIB_EXPORT int MyExportedFunction(int i);

} // namespace PLACEHOLDER_MYPROJ_MYLIB

#endif // __PLACEHOLDER_MYPROJ_MYLIB_HPP__
