#ifndef __PLACEHOLDER_MYPROJ_MYSTATICLIB_HPP__
#define __PLACEHOLDER_MYPROJ_MYSTATICLIB_HPP__

namespace PLACEHOLDER_MYPROJ_MYSTATICLIB
{

int TestFunc(int i);

} // namespace PLACEHOLDER_MYPROJ_MYSTATICLIB

#endif // !__PLACEHOLDER_MYPROJ_MYSTATICLIB_HPP__
